name: Deploy to Mainnet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Install DFX
      run: |
        curl -fsSL https://internetcomputer.org/install.sh | sh -s -- -y
        echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH
        
    - name: Verify DFX installation
      run: |
        export PATH="$HOME/.local/share/dfx/bin:$PATH"
        dfx --version
        
    - name: Install candid-extractor
      run: cargo install candid-extractor
        
    - name: Install dependencies
      run: |
        npm install
        cd frontend && npm install
        
    - name: Build frontend
      run: |
        cd frontend
        npm run build
        cd ..
        
    - name: Setup DFX identity
      run: |
        export PATH="$HOME/.local/share/dfx/bin:$PATH"
        dfx identity new ci-identity --storage-mode plaintext || true
        dfx identity use ci-identity
        
    - name: Import DFX identity from secrets
      run: |
        echo "${{ secrets.DFX_IDENTITY_PEM }}" > ~/.config/dfx/identity/ci-identity/identity.pem
        chmod 600 ~/.config/dfx/identity/ci-identity/identity.pem
        
    - name: Run mainnet deployment script
      run: |
        export PATH="$HOME/.local/share/dfx/bin:$PATH"
        chmod +x docs/technical/mainnet_deploy.sh
        ./docs/technical/mainnet_deploy.sh
