name: Test Identity Import

on:
  workflow_dispatch:

jobs:
  test-identity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install DFX
      run: |
        DFX_VERSION=0.28.0
        wget https://github.com/dfinity/sdk/releases/download/${DFX_VERSION}/dfx-${DFX_VERSION}-x86_64-linux.tar.gz
        tar -xzf dfx-${DFX_VERSION}-x86_64-linux.tar.gz
        mkdir -p $HOME/.local/bin
        mv dfx $HOME/.local/bin/dfx
        chmod +x $HOME/.local/bin/dfx
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Test identity import
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        mkdir -p ~/.config/dfx/identity/chainnotary-mainnet/
        echo "${{ secrets.DFX_IDENTITY_PEM }}" > ~/.config/dfx/identity/chainnotary-mainnet/identity.pem
        chmod 600 ~/.config/dfx/identity/chainnotary-mainnet/identity.pem
        dfx identity use chainnotary-mainnet
        echo "Principal ID: $(dfx identity get-principal)"